### ISSUE TITLE
No compiler error from method with variant

### ISSUE THREAD

**Issue by hellos3b** [paarthenon/variant#16]
Love the library, been using it the last couple days (in gamedev too! saw you mention it)

Ran into a little thing though: 
1. Given a variant module of *Animal* with a variant *Dog*
2. If you create a function that only accepts *Dog*
3. And use it point-free in a context that uses *Animal*
4. The compiler doesn't raise an error

Variants:
```ts
  import { variantModule, VariantOf, TypeNames } from "variant";

  const Animal = variantModule({
    dog: {},
    cat: {}
  });

  type Animal<T extends TypeNames<typeof Animal> = undefined> = 
    VariantOf<typeof Animal, T>;
```

Issue:
```ts
  // an array of Animals
  declare const arrayOfAnyAnimal: Animal[];

  // Bark function for dogs only
  declare function bark(dog: Animal<'dog'>): Animal;

  // (expected): Error: Argument of type 'SumType....
  arrayOfAnyAnimal.map((i) => bark(i));

  // (unexpected): No compiler error
  arrayOfAnyAnimal.map(bark);
```

I'm wondering if this is fixable, or if there's at least some kind of workout to make the parameter of `bark(dog)` more strict?

**Comment by paarthenon** [comment]
Hi there! Could you let me know what version of TypeScript and Variant this is referencing? I'm using Variant 2.1 with TS 4.1 and I am experiencing a compiler error on the last line as you might expect. 

>  `Type '{ type: "cat"; }' is not assignable to type '{ type: "dog"; }'.ts(2345)`

Full error:
```
Argument of type '(dog: { type: "dog"; }) => SumType<{ dog: VariantCreator<"dog", () => {}, "type">; cat: VariantCreator<"cat", () => {}, "type">; }, "type">' is not assignable to parameter of type '(value: SumType<{ dog: VariantCreator<"dog", () => {}, "type">; cat: VariantCreator<"cat", () => {}, "type">; }, "type">, index: number, array: SumType<...>[]) => SumType<...>'.
  Types of parameters 'dog' and 'value' are incompatible.
    Type 'SumType<{ dog: VariantCreator<"dog", () => {}, "type">; cat: VariantCreator<"cat", () => {}, "type">; }, "type">' is not assignable to type '{ type: "dog"; }'.
      Type '{ type: "cat"; }' is not assignable to type '{ type: "dog"; }'.ts(2345)
```

If you are indeed using these same versions, it might be a compiler caching issue. Could you try `ctrl+shift+P` and then select the `TypeScript: Restart TS Server` option. 

Thanks for trying out the library. I hope we can get this figured out.

**Comment by hellos3b** [comment]
Hey, I'm on Variant 2.1.0 and TS 4.2.3

I've also got an example of it on code sandbox: https://codesandbox.io/s/typescript-forked-gjgvk?file=/src/index.ts:283-284

**Comment by paarthenon** [comment]
I believe this has to do with the `strictFunctionTypes` tsconfig flag. 

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types

Enabling that flag in your code sandbox looks like it will raise the error. I tend to run with `"strict": true,`

**Comment by hellos3b** [comment]
Ah, sweet! Always forget about that setting, thanks for reminding me.
