### ISSUE TITLE
Shoutout!

### ISSUE THREAD

**Issue by mikecann** [paarthenon/variant#47]
Not really an issue but I thought you might like to know that I gave this awesome lib a shoutout in this months blog post: https://mikecann.co.uk/posts/discriminated-unions-and-pattern-matching-in-typescript

Keep up the excellent work @paarthenon :)

**Comment by paarthenon** [comment]
Thanks Mike! That's a well-written article, and it's wonderful to see these examples of use in the wild. I apply matching in much the same ways :). 

I really appreciate the shoutout. Some more people have found their way to the library in the past couple of days, and I attribute that directly to you.

**Comment by mikecann** [comment]
Aww thanks for the compliments. I hope your health is continuing to recover.

If you ever want to chat about anything my can find my email on my blog :)
