### ISSUE TITLE
Change the `type` field

### ISSUE THREAD

**Issue by yovanoc** [paarthenon/variant#8]
I think it could be a good idea to change the `type` field by another name like `__typename` or other to follow graphql or other existing codebase

thanks

**Comment by paarthenon** [comment]
Hi @yovanoc 

`type` is just the default. You can change it to what your app needs.

Most of the types and functions should have an optional property that overrides the key they pivot on. You can make a new constructor function to use this type by calling `variantFactory`.

```typescript
const myVariant = variantFactory('__typename');
type KEY = '__typename';

export const Animal = variantList([
    myVariant('Dog', fields<{name: string, favoriteBall?: string}>()),
    myVariant('Cat', fields<{name: string, daysSinceDamage: number}>()),
    myVariant('Snake', (name: string, pattern = 'striped') => ({name, pattern})),
]);
export type Animal<T extends TypeNames<typeof Animal, KEY> = undefined> = VariantOf<typeof Animal, T, KEY>;
```

type `Animal<'Dog'>` is rendered as:
```typescript
{
    __typename: "Dog";
    name: string;
    favoriteBall?: string | undefined;
}
```
and match, too.
```typescript
const result = match(animal, {
    Cat: ...
    Dog: ...
    Snake: ...
}, '__typename')
```
I figured somebody would want to do something like this, or be picky about `type` vs. `tag` vs. `kind`, or as you mention, `__typename`. I had to pick one, so I picked the one with the best ergonomics (`type`) and left options for overriding it. Hope that helps.

**Comment by yovanoc** [comment]
Perfect! thanks for your time

**Comment by paarthenon** [comment]
Absolutely! Thank you for using the library. Closing for now, feel free to reopen or raise a new issue if something comes up. I suspect there are some functions I forgot to give the `typeKey?: K` treatment. I'm actively working on `2.0.2-beta.4`+ available through `npm i variant@beta` so if you point out any missing elements, changes will likely show up there first.
